default_context:
    author: "example"
    email: "example@example.com"
    author_github_handle: "example"
    project_name: "ml-pacakge"
    project_slug: "{{cookiecutter.project_name|lower|replace('-', '_')}}"
    project_description: "example ml package"
    include_github_actions: "y"
    publish_to: ["pypi", "artifactory", "none"]
    deptry: "y"
    mkdocs: "y"
    codecov: "y"
    dockerfile: "y"
    devcontainer: "y"
    open_source_license: "MIT license"
#cookiecutters_dir: "example-dir"
#replay_dir: "example-dir"
abbreviations:
    pp: https://github.com/audreyr/cookiecutter-pypackage.git
    gh: https://github.com/{0}.git
    bb: https://bitbucket.org/{0}


