include:
  - docker-compose-batch.yaml
  - docker-compose-analytics.yaml
  - docker-compose-stream.yaml
  - docker-compose-stream-analytics.yaml
  - docker-compose-data-stores.yaml
  - docker-compose-logging.yaml
  - docker-compose-overlay-jaffle_shop.yaml

networks:
  analytics_net:
    driver: bridge
  stream_net:
    driver: bridge
  batch_net:
    driver: bridge
  db_net:
    driver: bridge

