services:
  postgres-db:
    # deployment - container
    container_name: postgres-db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: public
    # deployment - volumes
    volumes:
      - volumes-postgres-db:/var/lib/postgresql/data
    # service - ports
    ports:
      - "55432:5432"
    # others
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    networks:
      db_net:

  mongo-db:
    # deployment - container
    container_name: mongo-db
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    # deployment - volumes
    volumes:
      - volumes-mongo-db:/data/db
    # service - ports
    ports:
      - "27017:27017"
    # others
    networks:
      db_net:

volumes:
  volumes-postgres-db:
  volumes-mongo-db:
