include:
  - shared-config.yaml
  - docker-compose-data-batch.yaml
  - docker-compose-data-analytics.yaml
  - docker-compose-data-database.yaml
  - docker-compose-data-stream.yaml
  - docker-compose-data-stream-analytics.yaml
  - docker-compose-ml-datastore.yaml
  - docker-compose-ml-mlflow.yaml
  - docker-compose-ml-tensorflow.yaml
  - docker-compose-monitoring.yaml
  - docker-compose-app-jaffle_shop.yaml

networks:
  analytics_net:
    driver: bridge
  stream_net:
    driver: bridge
  batch_net:
    driver: bridge
  db_net:
    driver: bridge
  mlflow-net:
    driver: bridge



