x-common-environment: &common-environment
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
    MINIO_REGION: us-east-1

services:
  dz-minio:
    # deployment - container
    container_name: dz-minio
    image: minio/minio
    command: [ "server", "/data", "--console-address", ":9001" ]
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_DOMAIN: minio
    # deployment - volumes
    volumes:
      - volumes-dz-minio:/data
    # service - ports
    ports:
      - "19000:9000"
      - "19001:9001"
    # others
    networks:
      - batch_net
      - analytics_net
      - stream_net
      - db_net
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 30s
      timeout: 20s
      retries: 3

  dz-mc:
    # deployment - container
    container_name: dz-mc
    image: minio/mc
    environment:
      <<: *common-environment
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://dz-minio:9000 minio minio123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse mb minio/warehouse;
      /usr/bin/mc anonymous set download minio/warehouse;
      tail -f /dev/null
      "
    # deployment - volumes
    volumes:
      - volumes-dz-mc:/root/.mc
    # service - ports
    ports:
      - 19002:9000
    # others
    depends_on:
      - dz-minio
    networks:
      - batch_net
      - analytics_net
      - stream_net
      - db_net

volumes:
    volumes-dz-minio:
    volumes-dz-mc: