services:
  postgres-mlflow:
    container_name: postgres-mlflow
    image: postgres:13
    environment:
      POSTGRES_USER: ml_user
      POSTGRES_PASSWORD: ml_password
      POSTGRES_DB: ml_data
    volumes:
      - volumes-postgres-db:/var/lib/postgresql/data
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "25432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ml_user -d ml_data" ]
      interval: 5s
      retries: 5
    networks:
      - mlflow-net

  mlflow-server:
    image: bitnami/mlflow:latest
    container_name: ml_tracking
    ports:
      - "15000:8080"
    networks:
      - mlflow-net
    environment:
      - MLFLOW_SERVE_ARTIFACTS=true
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - MLFLOW_S3_ENDPOINT_URL=http://mlflow-artifact-minio:29000
      - MLFLOW_S3_IGNORE_TLS=true
    command:
      - /opt/bitnami/python/bin/mlflow
      - server
      - --host=0.0.0.0
      - --port=8080
      - --backend-store-uri=postgresql://ml_user:ml_password@postgres-mlflow:25432/ml_data
      - --default-artifact-root=s3://mlflow-artifacts/
    volumes:
      - volumes-mlflow-server:/mlruns
    depends_on:
      postgres-db:
        condition: service_healthy
      mlflow-artifact-minio:
        condition: service_healthy

  mlflow-artifact-minio:
    container_name: mlflow-artifact-minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DOMAIN: minio
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - volumes-mlflow-artifact-minio:/data
    ports:
      - "29000:9000"
      - "29001:9001"
    networks:
      - mlflow-net
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 30s
      timeout: 20s
      retries: 3

  mc-init:
    image: minio/mc
    depends_on:
      mlflow-artifact-minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://mlflow-artifact-minio:29000 minio minio123 &&
      mc mb myminio/mlflow-artifacts --ignore-existing &&
      mc mb myminio/data-staging --ignore-existing &&
      mc policy set public myminio/mlflow-artifacts &&
      mc policy set public myminio/data-staging
      "
    networks:
      - mlflow-net
  
  fastapi:
    build:
      context: ./shared/fastapi
      dockerfile: Dockerfile
    container_name: fastapi-server
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:15000
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_ENDPOINT_URL=http://minio:29000
    depends_on:
      - mlflow-server
    volumes:
      - ./fastapi:/app
    networks:
      - mlflow-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  db_net:
    driver: bridge

volumes:
  volumes-postgres-mlflow:
  volumes-mlflow-server:
  volumes-mlflow-artifact-minio: