services:
  flink-jobmanager: # session mode
    # deployment - container
    container_name: flink-jobmanager
    image: flink:1.17.2-java11
    command:
      - jobmanager
      - mkdir -p /opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    # service - ports
    ports:
      - "8082:8081"
    # others
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8082" ]
    networks:
      analytics_net:

  flink-taskmanager:
    # deployment - container
    container_name: flink-taskmanager
    image: flink:1.17.2-java11
    ports:
      - "18081:8081"
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
    # deployment - volumes
    volumes:
      - volumes-flink-task-manager-file-sink:/opt/flink/output
    # others
    depends_on:
      - flink-jobmanager
    networks:
      analytics_net:

  flink-sql-client:
    # deployment - container
    container_name: flink-sql-client
    build:
      context: ./shared/flink/sql-client
    environment:
      FLINK_JOBMANAGER_HOST: flink-jobmanager
      KAFKA_BOOTSTRAP_SERVERS: kafka1:29092,kafka2:29092,kafka3:29092
      KAFKA_CONNECT: kafka-connect
      KAFKA_BOOTSTRAP: kafka-connect
      POSTGRES_HOST: postgres-db
      ES_HOST: logs-elasticsearch
    # service - ports
    ports:
      - "18083:8083"
    # others
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - flink-jobmanager
      - logs-elasticsearch
    networks:
      analytics_net:

volumes:
  volumes-flink-task-manager-file-sink: