# shared-config.yml
x-common: &common
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"

x-minio-environment: &minio-test-credentials
  AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-minio}
  AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:-minio123}
  AWS_REGION: ${AWS_REGION:-us-east-1}

x-minio-server: &minio-server-config
  MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
  MINIO_DOMAIN: ${MINIO_DOMAIN:-minio}

x-postgres-config: &postgres-test-credentials
  POSTGRES_USER: ${POSTGRES_USER:-admin}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  POSTGRES_HOST_AUTH_METHOD: md5

x-small-resources: &small-resources
  deploy:
    resources:
      reservations:
        cpus: '0.25'
        memory: 512M
      limits:
        cpus: '0.5'
        memory: 1G

x-medium-resources: &medium-resources
  deploy:
    resources:
      reservations:
        cpus: '0.5'
        memory: 1G
      limits:
        cpus: '1.0'
        memory: 2G

