jaffle_shop:
  outputs:
    dev:
      type: postgres
#      host: host.docker.internal
      host: postgres-db
      user: postgres
      password: password
      port: 55432
      dbname: jaffle_shop
      schema: public
      threads: 2
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 100 # default 10 seconds
      retries: 3  # default 1 retry on error/timeout when opening connections
#      search_path: [optional, override the default postgres search_path]
#      role: [optional, set the role dbt assumes when executing queries]
#      sslmode: [optional, set the sslmode used to connect to the database]
#      sslcert: [optional, set the sslcert to control the certifcate file location]
#      sslkey: [optional, set the sslkey to control the location of the private key]
#      sslrootcert: [optional, set the sslrootcert config value to a new file path in order to customize the file location that contain root certificates]
  target: dev

